#!/usr/bin/python2.7

import argparse
import sys
# import multisigrecovery.commands
# from multisigrecovery.commands import ScriptInputError
from tests.test_cycle import test_cycle
# from tests.test_signing import test_signing

INSIGHT_LOCALHOST_URL = 'http://127.0.0.1:4001/'


def main():
	parser = argparse.ArgumentParser(description='BitOasis multisig branch recovery script', formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument('command', choices=['cycle'])
	parser.add_argument('--insight', metavar='URL', help='Default: http://127.0.0.1:4001/ (create, broadcast)', default=INSIGHT_LOCALHOST_URL)
	args = parser.parse_args()

	if args.insight == INSIGHT_LOCALHOST_URL:
		print "Using %s for insight, use '--insight URL' to change" % INSIGHT_LOCALHOST_URL

	if args.command == 'cycle':
		test_cycle(args.insight)

	# elif args.command == 'signing':
	# 	test_signing(args.insight)


if __name__ == '__main__':
	main()
